services:
- type: web
  name: flask-postgres-api
  env: python
  repo: https://github.com/uwidcit/flaskmvc.git
  plan: free
  branch: main
  healthCheckPath: /healthcheck
  buildCommand: "pip install -r requirements.txt"
  startCommand: "flask db upgrade && gunicorn wsgi:app"
  envVars:
  - key: SQLALCHEMY_DATABASE_URI
    value: postgresql://uwi_maps_db_user:38PY1JiZQJm8Ik5P6vxuDnWb41adWAzA@dpg-d00400vgi27c73atjo9g-a/uwi_maps_db
  - key: ENV
    value: production
  - key: FLASK_APP
    value: wsgi.py

databases:
- name: flask-postgres-api-db
  plan: free
  databaseName: mydb